language: node_js
node_js: "stable"

notifications:
  email: false

before_install:
  - stty cols 80

script: "npm run test:karma-remote"

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
